// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0s682mfIMGiZtPumHaaMPUX9_xIu2pyw',
    appId: '1:524899117388:web:fbb776b9d679010da087e9',
    messagingSenderId: '524899117388',
    projectId: 'flutter-fb-v2',
    authDomain: 'flutter-fb-v2.firebaseapp.com',
    storageBucket: 'flutter-fb-v2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5hF62bFva9Cz4yf61TxTlvo8ylNFxT4E',
    appId: '1:524899117388:android:2647db27f9c61cb9a087e9',
    messagingSenderId: '524899117388',
    projectId: 'flutter-fb-v2',
    storageBucket: 'flutter-fb-v2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdUWvkyKti5fDiX8gpDzUknkj76ORBlu0',
    appId: '1:524899117388:ios:567acfc3f70cc464a087e9',
    messagingSenderId: '524899117388',
    projectId: 'flutter-fb-v2',
    storageBucket: 'flutter-fb-v2.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdUWvkyKti5fDiX8gpDzUknkj76ORBlu0',
    appId: '1:524899117388:ios:486a757c545f9c93a087e9',
    messagingSenderId: '524899117388',
    projectId: 'flutter-fb-v2',
    storageBucket: 'flutter-fb-v2.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
