// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt5aHJlNsBxnjvztAXGb5TK006_bppvDQ',
    appId: '1:73835003784:web:2b6429ed098379b281443d',
    messagingSenderId: '73835003784',
    projectId: 'fir-flutter-v5',
    authDomain: 'fir-flutter-v5.firebaseapp.com',
    storageBucket: 'fir-flutter-v5.appspot.com',
    measurementId: 'G-57JZPM2LEX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGlteMUDO4P6Cx4ofV6_Ct658ZA26lqpU',
    appId: '1:73835003784:android:9491048efc1e657081443d',
    messagingSenderId: '73835003784',
    projectId: 'fir-flutter-v5',
    storageBucket: 'fir-flutter-v5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpkp7XId4J2rifIr1WzEQ_dRRWLHf1-ew',
    appId: '1:73835003784:ios:888d9021056756cc81443d',
    messagingSenderId: '73835003784',
    projectId: 'fir-flutter-v5',
    storageBucket: 'fir-flutter-v5.appspot.com',
    iosClientId: '73835003784-d3tf35ohqtp55dc2ghta2v674jp0lupk.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpkp7XId4J2rifIr1WzEQ_dRRWLHf1-ew',
    appId: '1:73835003784:ios:7e19a8140a64b9dd81443d',
    messagingSenderId: '73835003784',
    projectId: 'fir-flutter-v5',
    storageBucket: 'fir-flutter-v5.appspot.com',
    iosClientId: '73835003784-ia6gms8cuo2f0kjnn8m77o2pa10vsits.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
